# Generated by Django 3.1.2 on 2021-11-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_raw', models.TextField()),
                ('words_clean', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.JSONField()),
                ('dimensions', models.JSONField(null=True)),
                ('cross', models.JSONField(null=True)),
                ('down', models.JSONField(null=True)),
                ('ordering', models.JSONField(null=True)),
                ('words', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.wordlist')),
            ],
        ),
    ]
